# NUMPY
---

In [2]:
import numpy as np
np.__version__

'2.3.5'

In [2]:
# Create a numpy array with list 
list1 = [1,2,3,4,5]
type(list1)

list

In [3]:
arr1 = np.array(list1)
type(arr1)

numpy.ndarray

In [10]:
list2 = [10,20,30,40,50]
arr2 = np.array(list2)
arr2

array([10, 20, 30, 40, 50])

In [11]:
list1+list2

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [12]:
arr1+arr2

array([11, 22, 33, 44, 55])

### *Random module* 
---
In random module randint is a function in the random module of numpy library

In [17]:
# Create a random integer arrays 
arr3 = np.random.randint(1,100,2)
arr3

array([ 5, 92], dtype=int32)

In [19]:
arr4 = np.random.randint(1,10,(4,3))
arr4

array([[6, 5, 2],
       [9, 8, 3],
       [8, 8, 9],
       [3, 2, 3]], dtype=int32)

In [20]:
# Attribute of array
arr4.shape

(4, 3)

In [23]:
arr4.size

12

In [25]:
arr4.dtype

dtype('int32')

In [28]:
arr5 = np.arange(10)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr6 = np.arange(2,21,2)
arr6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
arr7 = np.random.randint(1,10,(5,4))
arr7

array([[9, 5, 1, 8],
       [6, 8, 9, 9],
       [5, 9, 8, 4],
       [3, 9, 6, 8],
       [6, 8, 1, 6]], dtype=int32)

In [34]:
arr7[0,0]

np.int32(9)

In [36]:
arr7[0,2]

np.int32(1)

In [43]:
arr7[::,0:4:2]

array([[9, 1],
       [6, 9],
       [5, 8],
       [3, 6],
       [6, 1]], dtype=int32)

## Array broadcasting

In [3]:
arr1 = np.random.randint(1,10,(3,4))
arr1

array([[7, 5, 6, 9],
       [3, 8, 7, 1],
       [4, 7, 5, 3]], dtype=int32)

In [7]:
arr2 = np.asarray([1,2,3,4])
arr2

array([1, 2, 3, 4])

In [9]:
arr2.shape

(4,)

In [8]:
arr1+arr2

array([[ 8,  7,  9, 13],
       [ 4, 10, 10,  5],
       [ 5,  9,  8,  7]])

In [10]:
arr3 = np.array([1,2])
arr3

array([1, 2])

In [11]:
arr3.shape

(2,)

In [ ]:
arr1+arr3 

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [16]:
arr1 = np.random.randint(1,10,(2,3))
arr1 

array([[8, 1, 5],
       [9, 1, 3]], dtype=int32)

In [17]:
arr2 = np.random.randint(1,10,(2,3))
arr2

array([[5, 9, 7],
       [9, 4, 2]], dtype=int32)

In [18]:
arr1 == arr2

array([[False, False, False],
       [ True, False, False]])

In [19]:
arr1 != arr2

array([[ True,  True,  True],
       [False,  True,  True]])

In [20]:
arr1 > arr2

array([[ True, False, False],
       [False, False,  True]])

In [22]:
np.array(arr1).T

array([[8, 9],
       [1, 1],
       [5, 3]], dtype=int32)

In [26]:
print("Vector of zeros:\n",np.zeros(5))
print('-' *30)

Vector of zeros:
 [0. 0. 0. 0. 0.]
------------------------------


In [30]:
print("11 linearly spaced numbers between 1 and 5: ",np.linspace(1,5,20))

11 linearly spaced numbers between 1 and 5:  [1.         1.21052632 1.42105263 1.63157895 1.84210526 2.05263158
 2.26315789 2.47368421 2.68421053 2.89473684 3.10526316 3.31578947
 3.52631579 3.73684211 3.94736842 4.15789474 4.36842105 4.57894737
 4.78947368 5.        ]


---
# PANDAS
---


In [4]:
import pandas as pd
pd.__version__

'2.3.3'

In [5]:
# Create a series 
s = pd.Series([1,2,3,4,5])
s   

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [7]:
s = pd.Series([1,2,3,4,5], index = ["a","b","c","d","e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [8]:
print(s["c"])

3


In [9]:
import numpy as np 
data = np.random.randint(1,100,25).reshape(5,5)
data

array([[ 7,  4,  2, 57, 39],
       [ 2, 47, 16, 52, 14],
       [22, 84, 77, 50, 42],
       [62, 10, 51, 20, 53],
       [ 2,  8, 90, 22, 47]], dtype=int32)

In [10]:
DF = pd.DataFrame(data, index = [1,2,3,4,5], columns = ["A","B","C","D","E"])
DF

,A,B,C,D,E
1,7,4,2,57,39
2,2,47,16,52,14
3,22,84,77,50,42
4,62,10,51,20,53
5,2,8,90,22,47
